analysis:
  features:
    dinov2:
      chunk-size: 1000
    clip-openai:
      batch-size: 1
      num-workers: 8

index:
  objects:
    exclude_labels:
      all: []
    min_area: 0.001
    threshold:
      monochrome: 0.01
      colors: 0.1
      frcnn-oiv4: 0.6
      mrcnn-lvis: 0.5
      vfnet64-coco: 0.5

  features:
    dinov2:
      index_engine: str
      index_type: topk-sq
      index_params:
        keep: 0.25
        dim_multiplier: 3.0
    clip-openai:
      index_engine: faiss
      index_type: Flat
