analysis:
  features:
    dinov2:
      chunk-size: 1000
    clip-openai:
      batch-size: 1
      num-workers: 8

index:
  features:
    dinov2:
      index_engine: str
      index_type: topk-sq
      index_params:
        keep: 0.25
        dim_multiplier: 3.0
    clip-openai:
      index_engine: faiss
      index_type: Flat
